# Generated by Django 2.1.5 on 2019-02-01 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20190124_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='bounces',
        ),
        migrations.RemoveField(
            model_name='group',
            name='subs',
        ),
        migrations.AddField(
            model_name='group',
            name='subs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='subscribe.Subscriber'),
            preserve_default=False,
        ),
    ]
