# Generated by Django 2.1.5 on 2019-02-01 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0006_auto_20190201_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subs',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='subscribe.Group'),
            preserve_default=False,
        ),
    ]
