# Generated by Django 2.1.5 on 2019-02-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0008_auto_20190201_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('bounced', 'bounced'), ('complaint', 'complaint')], default='available', max_length=100),
        ),
    ]
