# Generated by Django 2.1.5 on 2019-01-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('sentTo', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('edited_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DraftAttachments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='attachments/%y-%m')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='draft.Draft')),
            ],
        ),
    ]
