# Generated by Django 2.1.5 on 2019-01-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default='', upload_to='attachments/%y-%m')),
            ],
        ),
        migrations.RemoveField(
            model_name='draftattachments',
            name='draft',
        ),
        migrations.DeleteModel(
            name='DraftAttachments',
        ),
        migrations.AddField(
            model_name='draft',
            name='files',
            field=models.ManyToManyField(related_name='drafts', to='draft.Attachment'),
        ),
    ]
