# Generated by Django 2.1.5 on 2019-01-24 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_auto_20190123_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draft',
            name='files',
        ),
        migrations.AddField(
            model_name='attachment',
            name='draft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='draft.Draft'),
            preserve_default=False,
        ),
    ]
