# Generated by Django 2.1.5 on 2019-01-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_auto_20190124_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draft',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
