# Generated by Django 2.1.5 on 2019-01-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_auto_20190127_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
