# Generated by Django 2.1.5 on 2019-02-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0006_auto_20190128_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
