# Generated by Django 2.1.5 on 2019-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0007_draft_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='sentTo',
            field=models.TextField(default=''),
        ),
    ]
