# Generated by Django 2.1.5 on 2019-07-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0008_auto_20190629_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='group',
            field=models.TextField(default=''),
        ),
    ]
