# Generated by Django 2.1.5 on 2019-02-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('sent', models.IntegerField()),
                ('rejects', models.IntegerField()),
                ('complaints', models.IntegerField()),
                ('bounces', models.IntegerField()),
            ],
        ),
    ]
