# Generated by Django 2.1.5 on 2019-01-28 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190128_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
