# Generated by Django 2.1.5 on 2019-01-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_news_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='flag',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
