# Generated by Django 2.1.5 on 2019-06-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('middlename', models.CharField(blank=True, max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('passport_photo', models.ImageField(upload_to='resume_photos')),
                ('resume', models.FileField(upload_to='resumes')),
                ('important', models.BooleanField(default=False)),
            ],
        ),
    ]
