# Generated by Django 2.1.5 on 2019-01-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.CharField(max_length=100)),
                ('subject', models.CharField(default='not yet updated', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('noSubs', models.IntegerField(default=0)),
                ('bounces', models.IntegerField(default=0)),
                ('complaints', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SendQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('msgId', models.CharField(default='no return yet', max_length=100)),
                ('sent', models.BooleanField(default=False)),
                ('status', models.CharField(default='delivery', max_length=100)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendq', to='outbox.Outbox')),
            ],
        ),
    ]
