# Generated by Django 2.1.5 on 2019-01-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20190124_2018'),
        ('outbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outbox',
            name='bounces',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='complaints',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='noSubs',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='subject',
        ),
        migrations.AddField(
            model_name='outbox',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox', to='subscribe.Group'),
        ),
        migrations.AlterField(
            model_name='outbox',
            name='draft',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbox', to='subscribe.Subscriber'),
        ),
    ]
