# Generated by Django 2.1.5 on 2019-01-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0002_auto_20190129_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outbox',
            name='draft',
            field=models.IntegerField(default=33),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outbox',
            name='group',
            field=models.IntegerField(default=26),
            preserve_default=False,
        ),
    ]
