# Generated by Django 2.1.5 on 2019-01-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0005_auto_20190124_2018'),
        ('outbox', '0003_auto_20190129_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.IntegerField(null=True)),
                ('subs', models.ManyToManyField(related_name='batch', to='subscribe.Subscriber')),
            ],
        ),
        migrations.RemoveField(
            model_name='sendq',
            name='outbox',
        ),
        migrations.DeleteModel(
            name='SendQ',
        ),
    ]
