# Generated by Django 2.1.5 on 2019-01-29 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0004_auto_20190129_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
